FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r docker/requirements_deploy.txt
RUN pip install flask

EXPOSE 8080
ENV PORT=8080
RUN chmod +x src/stats.py docker/service.py

CMD python src/stats.py & python docker/service.py
