FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r docker/requirements_deploy.txt
RUN pip install flask
EXPOSE 8080

ENV PORT=8080

CMD ls app/ & python docker/service.py
