name: Deploy to Google Cloud Run

on:
  pull_request:
    branches: [ "main" ]  # Trigger the workflow on push to main branch

env:
  PROJECT_ID: local-network-435015
  GAR_NAME: jobtests
  GAR_LOCATION: us-east1
  SERVICE_NAME: ltchallenge  # TODO: update this to your Cloud Run service name
  REGION: us-east1  # TODO: update this to your preferred region

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Docker auth
      run: |
        gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"

    - name: Build and Push Docker image
      run: |
        docker build -f docker/Dockerfile.deploy -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        flags: '--timeout=3600 --cpu=1 --memory=8048Mi'
        
    - name: Delete existing Cloud Run service
      run: |
        gcloud run services delete "${{ env.SERVICE_NAME }}" --region "${{ env.REGION }}" --quiet || true
